// <auto-generated />
#nullable enable
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace ZAdmin.WebView.Core.Generated;

public static class WebViewProtocol
{
    public const int Version = 1;
    public const int MaxMessageBytes = 1048576;
    public const string AppSnapshot = "app.snapshot";
    public const string ClipboardClear = "clipboard.clear";
    public const string ClipboardReadText = "clipboard.readText";
    public const string ClipboardWriteText = "clipboard.writeText";
    public const string DialogOpen = "dialog.open";
    public const string DialogSave = "dialog.save";
    public const string FilesystemExists = "filesystem.exists";
    public const string FilesystemReadText = "filesystem.readText";
    public const string FilesystemRemove = "filesystem.remove";
    public const string FilesystemWriteText = "filesystem.writeText";
    public const string LogWrite = "log.write";
    public const string NotificationPermission = "notification.permission";
    public const string NotificationRequestPermission = "notification.requestPermission";
    public const string NotificationSend = "notification.send";
    public const string OpenerOpenUrl = "opener.openUrl";
    public const string OsSnapshot = "os.snapshot";
    public const string ProcessExit = "process.exit";
    public const string ProcessRelaunch = "process.relaunch";
    public const string StoreClear = "store.clear";
    public const string StoreDelete = "store.delete";
    public const string StoreGet = "store.get";
    public const string StoreKeys = "store.keys";
    public const string StoreSave = "store.save";
    public const string StoreSet = "store.set";
    public const string UpdaterCheck = "updater.check";
    public const string WindowClose = "window.close";
    public const string WindowMaximize = "window.maximize";
    public const string WindowMinimize = "window.minimize";
    public const string WindowRestore = "window.restore";
    public const string WindowSnapshot = "window.snapshot";
    public const string WindowStartDragging = "window.startDragging";
    public const string WindowToggleMaximize = "window.toggleMaximize";
    public const string WindowStateRestore = "windowState.restore";
    public const string WindowStateSave = "windowState.save";
    public static readonly IReadOnlySet<string> Methods = new HashSet<string>(StringComparer.Ordinal)
    {
        AppSnapshot,
        ClipboardClear,
        ClipboardReadText,
        ClipboardWriteText,
        DialogOpen,
        DialogSave,
        FilesystemExists,
        FilesystemReadText,
        FilesystemRemove,
        FilesystemWriteText,
        LogWrite,
        NotificationPermission,
        NotificationRequestPermission,
        NotificationSend,
        OpenerOpenUrl,
        OsSnapshot,
        ProcessExit,
        ProcessRelaunch,
        StoreClear,
        StoreDelete,
        StoreGet,
        StoreKeys,
        StoreSave,
        StoreSet,
        UpdaterCheck,
        WindowClose,
        WindowMaximize,
        WindowMinimize,
        WindowRestore,
        WindowSnapshot,
        WindowStartDragging,
        WindowToggleMaximize,
        WindowStateRestore,
        WindowStateSave,
    };
}

public sealed record ProtocolRequest(
    [property: JsonPropertyName("v")] int Version,
    [property: JsonPropertyName("kind")] string Kind,
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("method")] string Method,
    [property: JsonPropertyName("params")] JsonNode? Params);

public sealed record ProtocolError(
    [property: JsonPropertyName("code")] string Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("operation")] string Operation,
    [property: JsonPropertyName("retryable")] bool Retryable);
