// Generated by scripts/generate-catalog-manifest.mjs. Do not edit.
export interface ComponentCatalogManifestEntry {
	readonly id: string;
	readonly name: string;
	readonly category: string;
	readonly summary: string;
	readonly status: string;
	readonly keywords: readonly string[];
	readonly profiles: readonly string[];
	readonly capabilities: readonly string[];
	readonly demoCount: number;
	readonly publicComponentCount: number;
}

export const componentCategories = Object.freeze([
	{ id: 'gene', label: '通用组件' },
	{ id: 'layout', label: '布局组件' },
	{ id: 'input', label: '输入组件' },
	{ id: 'navigation', label: '导航组件' },
	{ id: 'overlay', label: '浮层组件' },
	{ id: 'data-display', label: '展示组件' },
	{ id: 'feedback', label: '反馈组件' },
	{ id: 'utility', label: '工具组件' }
] as const);

export const componentCatalogManifest = Object.freeze([
	{
		id: 'provider',
		name: 'ZProvider',
		category: 'gene',
		summary:
			'无额外DOM的作用域服务，统一提供Theme、显示偏好、区域设置、SSR稳定标识和Portal/ICSS边界。',
		status: 'stable',
		keywords: [],
		profiles: ['service'],
		capabilities: [
			'composition',
			'controlled',
			'density',
			'variants-and-states',
			'portal',
			'basic-render',
			'full-motion',
			'reduced-motion',
			'rtl',
			'ssr',
			'locale',
			'resource-cleanup'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'box',
		name: 'ZBox',
		category: 'gene',
		summary: '零包装的div基础容器，原生属性、事件、class、style、ref与ICSS变量落到同一根节点。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: ['basic-render', 'composition', 'focus', 'native-props', 'variants-and-states'],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'stack',
		name: 'ZStack',
		category: 'layout',
		summary: '类型安全的Flex布局容器，支持方向、间距、对齐、分布和换行。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'variants-and-states',
			'rtl',
			'keyboard',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'grid',
		name: 'ZGrid',
		category: 'layout',
		summary: '用显式列轨道和响应式查询建立可组合的逻辑栅格，ZGridItem负责跨列、起始列与跨行。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'ssr',
			'variants-and-states',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 2
	},
	{
		id: 'group',
		name: 'ZGroup',
		category: 'layout',
		summary:
			'固定row的ZStack便利层，保留普通children顺序，提供响应式间距/对齐/换行以及唯一itemSizing轴的auto、grow、equal直接子项宽度策略。',
		status: 'experimental',
		keywords: ['group', 'row', 'flex', 'grow', 'equal width', 'wrap', 'responsive'],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'variants-and-states',
			'rtl',
			'ssr'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'overflow-list',
		name: 'ZOverflowList',
		category: 'layout',
		summary: '用真实CSS布局尺寸折叠集合，保留唯一item DOM、逻辑顺序、固定项目和可访问的溢出入口。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'variants-and-states',
			'rtl',
			'keyboard'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'app-shell',
		name: 'ZAppShell',
		category: 'layout',
		summary:
			'原生区域的CSS Grid应用壳：通过响应式轨道完成侧栏折叠和内容offset，明确main/root唯一滚动owner，并保留调用方的内容、路由与交互所有权。',
		status: 'experimental',
		keywords: [
			'app shell',
			'application layout',
			'header',
			'navbar',
			'aside',
			'footer',
			'scroll',
			'responsive',
			'rtl'
		],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'ssr',
			'rtl',
			'variants-and-states'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'center',
		name: 'ZCenter',
		category: 'layout',
		summary: '不测量内容的原生双轴居中容器；inline只控制外部格式，不改变居中算法。',
		status: 'experimental',
		keywords: ['center', 'flex', 'inline flex', 'alignment', 'layout'],
		profiles: ['primitive'],
		capabilities: ['basic-render', 'composition', 'native-props', 'rtl'],
		demoCount: 2,
		publicComponentCount: 1
	},
	{
		id: 'spacer',
		name: 'ZSpacer',
		category: 'layout',
		summary:
			'一个固定逻辑尺寸的普通div。它表达某一处显式留白，不会修改父布局的gap、也不充当自动弹性填充物。',
		status: 'experimental',
		keywords: ['spacer', 'space', 'inline size', 'block size', 'responsive', 'layout'],
		profiles: ['primitive'],
		capabilities: ['basic-render', 'composition', 'native-props', 'rtl', 'ssr'],
		demoCount: 2,
		publicComponentCount: 1
	},
	{
		id: 'scroll-area',
		name: 'ZScrollArea',
		category: 'layout',
		summary:
			'单一真实div滚动节点，提供原生键盘滚动、响应式高度、标准CSS滚动条和遵从动画偏好的controller。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'keyboard',
			'native-props',
			'composition',
			'ssr',
			'variants-and-states',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'steps',
		name: 'ZSteps',
		category: 'navigation',
		summary:
			'流程导航保留真实ol/li和原生按钮/链接。currentKey表达当前位置，items.status表达业务完成或错误；请求与完成时机由调用方决定。',
		status: 'experimental',
		keywords: ['steps', 'stepper', 'workflow', 'aria-current', 'request', 'typed key', 'rtl'],
		profiles: ['collection'],
		capabilities: [
			'basic-render',
			'accessible-name',
			'ssr',
			'variants-and-states',
			'controlled',
			'keyboard',
			'composition',
			'density',
			'full-motion',
			'reduced-motion',
			'rtl',
			'locale',
			'native-props'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'simple-grid',
		name: 'ZSimpleGrid',
		category: 'layout',
		summary:
			'普通children的等宽CSS Grid：未传minItemWidth时固定columns明确编排，传入minItemWidth后auto-fit优先适应可用空间；它不提供跨列、GridItem或布局上下文。',
		status: 'experimental',
		keywords: [
			'simple grid',
			'css grid',
			'auto-fit',
			'minmax',
			'responsive',
			'container query',
			'rtl'
		],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'ssr',
			'variants-and-states',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'breadcrumb',
		name: 'ZBreadcrumb',
		category: 'navigation',
		summary:
			'生产Breadcrumb保持具名nav/ol/li、typed key、真实路由链接、唯一当前文本、可访问的折叠祖先入口和窄屏/RTL自然换行。',
		status: 'experimental',
		keywords: ['breadcrumb', 'navigation', 'nav', 'ol', 'li', 'aria-current', 'typed key', 'rtl'],
		profiles: ['collection'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'native-props',
			'ssr',
			'composition',
			'variants-and-states',
			'rtl',
			'locale'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'text',
		name: 'ZText',
		category: 'gene',
		summary: '把正文语义元素与字号、行高、字重、tone、单/多行省略和表格数字保持正交的文本原语。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: ['basic-render', 'native-props', 'variants-and-states', 'composition'],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'heading',
		name: 'ZHeading',
		category: 'gene',
		summary: '始终输出真实h1–h6，并明确分离文档层级与视觉字号、行高、字重、tone。',
		status: 'stable',
		keywords: ['heading', 'h1', 'h2', 'document outline', 'typography', 'semantic html'],
		profiles: ['primitive'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'native-props',
			'variants-and-states',
			'composition'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'icon',
		name: 'ZIcon',
		category: 'gene',
		summary: '基于Lucide静态子路径的受控图标原语，统一尺寸、ref与装饰/具名可访问语义。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'native-props',
			'accessible-name',
			'variants-and-states',
			'keyboard',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'code',
		name: 'ZCode',
		category: 'gene',
		summary:
			'SSR先输出纯文本，客户端generation-safe按需加载Shiki高对比tokens，并可组合安全、可本地化的复制操作。',
		status: 'stable',
		keywords: ['code', 'shiki', 'syntax highlight', 'copy', 'clipboard', 'SSR', 'CSP'],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'resource-cleanup',
			'ssr',
			'composition',
			'native-props',
			'variants-and-states',
			'accessible-name',
			'keyboard',
			'locale'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'button',
		name: 'ZButton',
		category: 'gene',
		summary:
			'保留原生button、type/form与callback语义，以正交variant/tone、size/shape和宽度稳定ZSpinner loading提供生产操作合同。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive', 'animated'],
		capabilities: [
			'basic-render',
			'variants-and-states',
			'density',
			'disabled',
			'loading',
			'composition',
			'native-props',
			'resource-cleanup',
			'reduced-motion',
			'form-data',
			'form-reset',
			'accessible-name',
			'focus',
			'keyboard'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'toggle-button',
		name: 'ZToggleButton',
		category: 'gene',
		summary:
			'只拥有pressed/defaultPressed/onPressedChange状态，复用Button原生语义与variant、tone、size、shape视觉合同的独立双态操作。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive', 'animated'],
		capabilities: [
			'controlled',
			'disabled',
			'keyboard',
			'uncontrolled',
			'density',
			'native-props',
			'variants-and-states',
			'accessible-name',
			'focus',
			'external-clear'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'link',
		name: 'ZLink',
		category: 'gene',
		summary:
			'以必填href和真实anchor为唯一导航语义，显式分离外链图标、新窗口行为、安全rel、disabled与视觉tone/underline。',
		status: 'stable',
		keywords: [
			'link',
			'anchor',
			'external link',
			'new window',
			'download',
			'aria-current',
			'disabled link'
		],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'variants-and-states',
			'focus',
			'accessible-name',
			'native-props',
			'locale',
			'disabled',
			'keyboard'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'separator',
		name: 'ZSeparator',
		category: 'gene',
		summary: '保留原生/ARIA语义、装饰模式、名称、逻辑方向和currentColor高对比的最小Separator。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'native-props',
			'variants-and-states',
			'accessible-name',
			'composition',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'visually-hidden',
		name: 'ZVisuallyHidden',
		category: 'gene',
		summary: '只负责视觉裁切且保留辅助技术内容的span原语；不提供focusable或asChild模式。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'controlled',
			'variants-and-states',
			'native-props',
			'ssr'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'kbd',
		name: 'ZKbd',
		category: 'gene',
		summary: '只表达用户输入文本的原生kbd；组合、嵌套和平台替代文本由调用方显式组织。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: ['basic-render', 'composition', 'native-props', 'accessible-name', 'ssr'],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'aspect-ratio',
		name: 'ZAspectRatio',
		category: 'layout',
		summary: '用原生CSS aspect-ratio、严格正有限比例和父级宽度约束承载图片、视频、自定义或空内容。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'native-props',
			'variants-and-states',
			'composition',
			'accessible-name',
			'ssr'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'container',
		name: 'ZContainer',
		category: 'layout',
		summary:
			'用box-sizing安全的居中typed max-width和逻辑gutter建立内容边界，不承担Stack/Grid职责。',
		status: 'stable',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'native-props',
			'rtl',
			'density',
			'variants-and-states',
			'composition',
			'ssr'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'avatar',
		name: 'ZAvatar',
		category: 'data-display',
		summary:
			'以原生响应式img属性、竞态隔离的图片尝试、显式imageRef/load/error和稳定可访问fallback组成的Avatar。',
		status: 'stable',
		keywords: [
			'avatar',
			'image',
			'fallback',
			'srcset',
			'lazy image',
			'decorative image',
			'image race'
		],
		profiles: ['data-view'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'ssr',
			'variants-and-states',
			'composition',
			'loading',
			'native-props',
			'controlled',
			'external-clear'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'badge',
		name: 'ZBadge',
		category: 'data-display',
		summary:
			'Badge只表达附着于对象的通知数量或紧凑圆点；可读状态文本属于ZTag，不再让两个语义共享一套含混API。',
		status: 'stable',
		keywords: ['badge', 'count', 'dot', 'max', 'show zero', 'anchor', 'overlap', 'notification'],
		profiles: ['data-view', 'animated'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'full-motion',
			'locale',
			'variants-and-states',
			'rtl',
			'controlled',
			'reduced-motion',
			'resource-cleanup'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'card',
		name: 'ZCard',
		category: 'data-display',
		summary:
			'以默认中性div避免article泛滥，按固定media→header→body→footer→actions顺序组合语义内容面。',
		status: 'stable',
		keywords: ['card', 'surface', 'article', 'section', 'media', 'actions', 'loading'],
		profiles: ['data-view'],
		capabilities: [
			'basic-render',
			'variants-and-states',
			'composition',
			'accessible-name',
			'native-props',
			'loading'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'description-list',
		name: 'ZDescriptionList',
		category: 'data-display',
		summary:
			'DescriptionList只拥有dl/dt/dd、typed key、有限term/description/action snippets和响应式展示；手写children保留复杂原生分组，empty/loading位于dl之外。',
		status: 'stable',
		keywords: [
			'description list',
			'dl',
			'dt',
			'dd',
			'metadata',
			'typed key',
			'empty state',
			'responsive details'
		],
		profiles: ['collection', 'data-view'],
		capabilities: [
			'basic-render',
			'native-props',
			'accessible-name',
			'variants-and-states',
			'composition',
			'focus',
			'keyboard',
			'loading',
			'locale',
			'rtl'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'list',
		name: 'ZList',
		category: 'data-display',
		summary:
			'语义List只拥有ul/ol/li、typed key和有限rich/action snippets；手写children由调用方拥有li结构，empty/loading位于列表之外，大数据改用ZVirtualList。',
		status: 'stable',
		keywords: [
			'list',
			'ordered list',
			'semantic list',
			'typed key',
			'empty list',
			'loading list',
			'virtual list'
		],
		profiles: ['collection', 'data-view'],
		capabilities: [
			'basic-render',
			'native-props',
			'composition',
			'focus',
			'keyboard',
			'accessible-name',
			'loading',
			'locale',
			'variants-and-states',
			'rtl',
			'resource-cleanup'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'tag',
		name: 'ZTag',
		category: 'data-display',
		summary:
			'Tag是静态分类标签与可选remove动作；集合编辑、方向键和删除后焦点属于TagsInput，count/dot overlay属于Badge。',
		status: 'stable',
		keywords: ['tag', 'remove', 'label', 'locale', 'chip', 'long content', 'focus owner'],
		profiles: ['data-view'],
		capabilities: [
			'accessible-name',
			'controlled',
			'keyboard',
			'variants-and-states',
			'disabled',
			'composition',
			'density',
			'rtl',
			'focus',
			'locale'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'progress',
		name: 'ZProgress',
		category: 'data-display',
		summary:
			'共享同一范围、格式化、reduced-motion和Theme duration合同的原生line与语义circular进度。',
		status: 'stable',
		keywords: [
			'progress',
			'progressbar',
			'circle',
			'line',
			'indeterminate',
			'tone',
			'reduced motion'
		],
		profiles: ['data-view', 'animated'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'variants-and-states',
			'native-props',
			'reduced-motion',
			'resource-cleanup',
			'full-motion',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'meter',
		name: 'ZMeter',
		category: 'data-display',
		summary:
			'坚持原生meter：严格范围/阈值/value、本地化value text、平台最佳区间与高对比语义，不承担任务进度。',
		status: 'stable',
		keywords: ['meter', 'gauge', 'threshold', 'capacity', 'optimum', 'native meter'],
		profiles: ['data-view'],
		capabilities: ['accessible-name', 'basic-render', 'variants-and-states', 'native-props', 'ssr'],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'skeleton',
		name: 'ZSkeleton',
		category: 'data-display',
		summary:
			'从可访问树隐藏、支持有限shape/严格尺寸/等尺寸多行，并以Theme WAAPI pulse或静态reduced模式工作的Skeleton原语。',
		status: 'stable',
		keywords: ['skeleton', 'placeholder', 'loading', 'lines', 'static', 'reduced motion'],
		profiles: ['animated'],
		capabilities: [
			'basic-render',
			'reduced-motion',
			'variants-and-states',
			'composition',
			'resource-cleanup',
			'full-motion',
			'native-props',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'empty',
		name: 'ZEmpty',
		category: 'data-display',
		summary:
			'面向集合无数据、筛选无结果或初次创建的中性Empty：真实ZHeading、装饰图标、原因说明与可选恢复操作。',
		status: 'stable',
		keywords: ['empty', 'no data', 'no results', 'first use', 'recovery', 'collection state'],
		profiles: ['data-view'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'keyboard',
			'variants-and-states',
			'native-props',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'timeline',
		name: 'ZTimeline',
		category: 'data-display',
		summary:
			'只呈现历史事件的真实ol/li集合：typed key、独立content/icon/time、状态tone、pending、reverse及RTL响应式alternate，不承担Steps导航。',
		status: 'stable',
		keywords: [
			'timeline',
			'ol',
			'li',
			'time',
			'typed key',
			'status',
			'pending',
			'reverse',
			'alternate',
			'rtl'
		],
		profiles: ['collection', 'data-view'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'native-props',
			'ssr',
			'composition',
			'variants-and-states',
			'loading',
			'rtl'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'statistic',
		name: 'ZStatistic',
		category: 'data-display',
		summary:
			'SSR稳定的静态指标：原生dl/data、Intl locale/precision、纯formatter、Snippet affix、有限tone、文字趋势与ZSkeleton loading。',
		status: 'stable',
		keywords: [
			'statistic',
			'intl',
			'locale',
			'precision',
			'formatter',
			'bigint',
			'trend',
			'loading'
		],
		profiles: ['data-view'],
		capabilities: [
			'basic-render',
			'locale',
			'ssr',
			'variants-and-states',
			'accessible-name',
			'composition',
			'native-props',
			'loading'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'table',
		name: 'ZTable',
		category: 'data-display',
		summary:
			'Table只拥有原生结构、caption、密度和有限横向scroll owner；数据模型、排序、选择、分页、请求和虚拟化属于ZDataTable或调用方。',
		status: 'stable',
		keywords: [
			'table',
			'caption',
			'thead',
			'tbody',
			'semantic',
			'responsive table',
			'horizontal scroll',
			'scope'
		],
		profiles: ['data-view'],
		capabilities: [
			'accessible-name',
			'composition',
			'focus',
			'basic-render',
			'native-props',
			'density',
			'variants-and-states',
			'resource-cleanup',
			'keyboard',
			'rtl'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'virtual-list',
		name: 'ZVirtualList',
		category: 'data-display',
		summary:
			'生产级纵向Virtual List：固定高度走低开销fast path，动态高度按typed key缓存真实测量，并用key锚定处理插入、排序和尺寸变化；controller只负责窗口与滚动，不拥有业务active或selection。',
		status: 'stable',
		keywords: [
			'virtual list',
			'virtualizer',
			'overscan',
			'dynamic height',
			'scroll anchor',
			'scrollToKey',
			'active descendant',
			'large data',
			'SSR',
			'ShadowRoot'
		],
		profiles: ['collection', 'data-view', 'virtualized'],
		capabilities: [
			'basic-render',
			'native-props',
			'variants-and-states',
			'resource-cleanup',
			'disabled',
			'focus',
			'keyboard',
			'reduced-motion',
			'rtl',
			'ssr',
			'accessible-name',
			'loading'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'data-table',
		name: 'ZDataTable',
		category: 'data-display',
		summary:
			'面向后台数据浏览的原生语义DataTable，负责稳定排序、行选择、自定义cell和可选固定行高虚拟化；请求、筛选、分页与异步状态由调用方组合。',
		status: 'stable',
		keywords: [
			'data table',
			'sort',
			'selection',
			'virtualization',
			'server controlled',
			'pagination',
			'filter',
			'custom cell',
			'loading',
			'empty',
			'error',
			'disabled row',
			'expanded row',
			'column visibility',
			'column resize',
			'sticky header'
		],
		profiles: ['collection', 'data-view', 'virtualized'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'controlled',
			'keyboard',
			'variants-and-states',
			'focus',
			'resource-cleanup',
			'ssr',
			'composition',
			'loading',
			'locale',
			'density',
			'disabled'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'carousel',
		name: 'ZCarousel',
		category: 'data-display',
		summary:
			'稳定typed-key、完整rotation controls、owner-realm可见性/计时器、typed locale与多原因暂停共同拥有的生产Carousel。',
		status: 'stable',
		keywords: [
			'carousel',
			'slides',
			'autoplay',
			'reduced motion',
			'rotation control',
			'locale',
			'RTL'
		],
		profiles: ['collection', 'animated'],
		capabilities: [
			'controlled',
			'keyboard',
			'variants-and-states',
			'disabled',
			'uncontrolled',
			'accessible-name',
			'full-motion',
			'reduced-motion',
			'resource-cleanup',
			'external-clear',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'alert',
		name: 'ZAlert',
		category: 'feedback',
		summary:
			'Alert是页面内持久、非阻塞反馈：统一tone、title/body/action/dismiss和显式live；Toast负责短暂队列通知，AlertDialog负责中断式确认。',
		status: 'stable',
		keywords: ['alert', 'status', 'live region', 'feedback', 'dismiss', 'high contrast'],
		profiles: ['primitive'],
		capabilities: [
			'accessible-name',
			'controlled',
			'keyboard',
			'native-props',
			'variants-and-states',
			'focus',
			'composition',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'loading-bar',
		name: 'ZLoadingBar',
		category: 'feedback',
		summary:
			'LoadingBar是轻量线性任务反馈：local/page布局、确定/不确定进度、bindable状态和作用域controller；请求、Promise、重试、路由和全局单例继续属于应用。',
		status: 'stable',
		keywords: [
			'loading bar',
			'progressbar',
			'page progress',
			'controller',
			'determinate',
			'indeterminate'
		],
		profiles: ['animated', 'service'],
		capabilities: [
			'accessible-name',
			'native-props',
			'variants-and-states',
			'composition',
			'reduced-motion',
			'resource-cleanup',
			'controlled',
			'external-clear',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'result',
		name: 'ZResult',
		category: 'feedback',
		summary:
			'用于重要操作处理结果的具名section：真实ZHeading、Alert同构tone、装饰图标、详细正文与后续操作保持独立。',
		status: 'stable',
		keywords: ['result', 'status page', 'success', 'operation outcome', 'heading', 'actions'],
		profiles: ['data-view'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'keyboard',
			'variants-and-states',
			'native-props',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'spinner',
		name: 'ZSpinner',
		category: 'feedback',
		summary:
			'Spinner只表达不确定等待：Lucide LoaderCircle、三个尺寸、有限tone、owner Window WAAPI和reduced-motion清理；容器、overlay、aria-busy与任务由消费者拥有。',
		status: 'stable',
		keywords: ['spinner', 'loading', 'reduced motion', 'WAAPI', 'owner Window'],
		profiles: ['animated'],
		capabilities: [
			'accessible-name',
			'reduced-motion',
			'variants-and-states',
			'composition',
			'resource-cleanup',
			'controlled',
			'keyboard'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'toast',
		name: 'ZToast',
		category: 'feedback',
		summary:
			'ZToast负责单条通知内容与操作；ZToaster负责把调用方拥有的ToastQueue连接到viewport、live region和Presence。需要跨页面通知时由服务层持有Queue，需要局部反馈时直接渲染ZToast；组件不创建全局单例。',
		status: 'stable',
		keywords: [
			'toast',
			'toaster',
			'notification',
			'live region',
			'queue',
			'partial update',
			'promise task',
			'assertive throttle'
		],
		profiles: ['animated', 'layer', 'service'],
		capabilities: [
			'basic-render',
			'portal',
			'resource-cleanup',
			'accessible-name',
			'variants-and-states',
			'full-motion',
			'controlled',
			'loading'
		],
		demoCount: 6,
		publicComponentCount: 2
	},
	{
		id: 'checkbox',
		name: 'ZCheckbox',
		category: 'input',
		summary: '保留原生checkbox、mixed状态、Field继承、readonly与FormData/reset合同的选择控件。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'form-reset',
			'uncontrolled',
			'density',
			'disabled',
			'invalid',
			'native-props',
			'focus',
			'keyboard',
			'readonly'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'checkbox-group',
		name: 'ZCheckboxGroup',
		category: 'input',
		summary: '真实ZCheckbox形成重复FormData，typed多选、组约束与mixed全选共享同一selection。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'controlled',
			'native-props',
			'invalid',
			'keyboard',
			'variants-and-states',
			'composition',
			'disabled',
			'density',
			'form-data',
			'form-reset',
			'readonly'
		],
		demoCount: 4,
		publicComponentCount: 3
	},
	{
		id: 'calendar',
		name: 'ZCalendar',
		category: 'input',
		summary:
			'统一single/multiple/range的Calendar，一个owner覆盖多月窗口、独立focusedValue、周号、范围preview与连续性约束；每月固定6周网格，跨月不重复交互日期。',
		status: 'stable',
		keywords: ['calendar', 'grid', 'focused value', 'calendar date', 'range', 'rtl'],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'controlled',
			'keyboard',
			'locale',
			'rtl',
			'accessible-name',
			'composition',
			'invalid',
			'variants-and-states',
			'basic-render',
			'form-data',
			'form-reset',
			'uncontrolled',
			'disabled',
			'focus',
			'ssr',
			'external-clear',
			'readonly'
		],
		demoCount: 10,
		publicComponentCount: 1
	},
	{
		id: 'mini-calendar',
		name: 'ZMiniCalendar',
		category: 'input',
		summary:
			'MiniCalendar是ZCalendar strip view的单日期便利入口；选择、焦点、日期约束、键盘和FormData仍只有一个Calendar owner。',
		status: 'experimental',
		keywords: ['mini calendar', 'date strip', 'calendar date', 'form', 'rtl'],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'basic-render',
			'controlled',
			'keyboard',
			'locale',
			'composition',
			'disabled',
			'rtl',
			'variants-and-states'
		],
		demoCount: 2,
		publicComponentCount: 1
	},
	{
		id: 'cascader',
		name: 'ZCascader',
		category: 'input',
		summary:
			'生产级单路径Cascader：LogicalTree只拥有层级，每列各自拥有Collection导航与DOM active，根统一管理路径、loaded search、lazy请求、Popover和FormValue。',
		status: 'stable',
		keywords: [
			'cascader',
			'logical tree',
			'active descendant',
			'lazy children',
			'loaded path search',
			'virtual column',
			'typed key',
			'form value'
		],
		profiles: ['collection', 'form-control', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'focus',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'controlled',
			'external-clear',
			'locale',
			'loading',
			'resource-cleanup',
			'ssr',
			'disabled',
			'invalid',
			'readonly',
			'rtl'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'color-picker',
		name: 'ZColorPicker',
		category: 'input',
		summary:
			'生产级单值ColorPicker：规范化hex/null、原生color/range、alpha、预设、清空、Field/FormValueBridge和Popover各自拥有清晰边界。',
		status: 'stable',
		keywords: [
			'color picker',
			'hex',
			'alpha',
			'null color',
			'presets',
			'native color',
			'popover',
			'form value'
		],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'form-reset',
			'keyboard',
			'locale',
			'external-clear',
			'focus',
			'disabled',
			'invalid',
			'readonly',
			'native-props'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'combobox',
		name: 'ZCombobox',
		category: 'input',
		summary:
			'生产单选Combobox：inputValue、value和open三轴独立，完整LogicalCollection在过滤与DOM挂载之外拥有顺序，ActiveDescendant只引用当前真实option。',
		status: 'stable',
		keywords: [
			'combobox',
			'autocomplete',
			'logical collection',
			'active descendant',
			'async',
			'remote',
			'group',
			'ime',
			'virtual list',
			'form reset'
		],
		profiles: ['form-control', 'collection', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'focus',
			'keyboard',
			'uncontrolled',
			'disabled',
			'controlled',
			'resource-cleanup',
			'loading',
			'locale',
			'portal',
			'external-clear',
			'readonly',
			'accessible-name',
			'rtl'
		],
		demoCount: 8,
		publicComponentCount: 4
	},
	{
		id: 'date-field',
		name: 'ZDateField',
		category: 'input',
		summary:
			'本地化CalendarDate分段字段：locale的Unicode ca扩展决定真实display calendar，编辑后转换回原owner calendar；同时保留nullable owner、草稿验证、边界、Field焦点与FormValueBridge。',
		status: 'stable',
		keywords: [
			'date field',
			'segments',
			'calendar date',
			'international calendar',
			'era',
			'locale',
			'form',
			'nullable'
		],
		profiles: ['form-control'],
		capabilities: [
			'controlled',
			'keyboard',
			'locale',
			'external-clear',
			'composition',
			'variants-and-states',
			'basic-render',
			'form-data',
			'form-reset',
			'uncontrolled',
			'accessible-name',
			'disabled',
			'readonly',
			'rtl',
			'focus',
			'invalid',
			'native-props'
		],
		demoCount: 8,
		publicComponentCount: 1
	},
	{
		id: 'date-picker',
		name: 'ZDatePicker',
		category: 'input',
		summary:
			'可编辑Date Picker：复用bare ZDateField、ZInputGroup、Lucide actions和owner-realm ZPopover/ZCalendar；value/open双owner、显式null、约束、clear/readonly/Field与唯一FormValueBridge。',
		status: 'stable',
		keywords: ['date picker', 'date field', 'calendar', 'popover', 'controlled', 'form'],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'composition',
			'variants-and-states',
			'basic-render',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'invalid',
			'readonly',
			'controlled',
			'external-clear',
			'portal',
			'resource-cleanup',
			'accessible-name',
			'locale',
			'rtl',
			'ssr',
			'focus',
			'native-props'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'date-range-picker',
		name: 'ZDateRangePicker',
		category: 'input',
		summary:
			'生产Date Range Picker：两个可编辑DateField、partial start/end、完整反向规范化、按端可用性、Calendar range preview、value/open双owner、typed locale/RTL和唯一双字段FormValueBridge。',
		status: 'stable',
		keywords: ['date range picker', 'partial range', 'calendar range', 'popover', 'rtl', 'form'],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'composition',
			'variants-and-states',
			'basic-render',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'invalid',
			'readonly',
			'controlled',
			'external-clear',
			'focus',
			'native-props',
			'accessible-name',
			'locale',
			'portal',
			'resource-cleanup',
			'rtl',
			'ssr'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'input',
		name: 'ZInput',
		category: 'input',
		summary:
			'原生input语义、Svelte bindable值、Field状态、外部form关联和唯一owner reset的稳定文本控件。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'uncontrolled',
			'density',
			'disabled',
			'native-props',
			'form-data',
			'form-reset',
			'focus',
			'invalid',
			'readonly'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'input-group',
		name: 'ZInputGroup',
		category: 'input',
		summary:
			'拥有一个业务control注册位并桥接Field label/focus/id/name/description/state/size的Input Group，严格区分非交互affix与真实action。',
		status: 'stable',
		keywords: [
			'input group',
			'input adornment',
			'prefix',
			'suffix',
			'action',
			'Field owner',
			'focus within',
			'form data',
			'rtl'
		],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'accessible-name',
			'form-data',
			'form-reset',
			'native-props',
			'disabled',
			'focus',
			'invalid',
			'rtl',
			'readonly'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'mention',
		name: 'ZMention',
		category: 'input',
		summary:
			'光标感知的原生textarea Mention：LogicalCollection和ActiveDescendant拥有typed建议，外部owner可异步更新结果，固定行窗口支持大型目录。',
		status: 'stable',
		keywords: [
			'mention',
			'textarea',
			'trigger',
			'caret',
			'active descendant',
			'async suggestions',
			'virtual suggestions',
			'IME'
		],
		profiles: ['collection', 'form-control', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'focus',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'locale',
			'controlled',
			'disabled',
			'external-clear',
			'readonly',
			'loading',
			'resource-cleanup',
			'ssr'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'multi-select',
		name: 'ZMultiSelect',
		category: 'input',
		summary:
			'生产多选集合：value统一数组主值命名，LogicalCollection拥有完整typed-key顺序，SelectionModel拥有toggle，ActiveDescendant拥有容器焦点，ZTag、Popover、VirtualList与FormValueBridge分别承接摘要、浮层、大数据窗口和提交。',
		status: 'stable',
		keywords: [
			'multi select',
			'listbox',
			'logical collection',
			'multiple selection',
			'active descendant',
			'typed key',
			'tag overflow',
			'virtual list',
			'async orphan',
			'form reset'
		],
		profiles: ['form-control', 'collection', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'controlled',
			'disabled',
			'loading',
			'locale',
			'portal',
			'external-clear',
			'focus',
			'resource-cleanup',
			'accessible-name',
			'readonly'
		],
		demoCount: 6,
		publicComponentCount: 4
	},
	{
		id: 'number-field',
		name: 'ZNumberField',
		category: 'input',
		summary:
			'面向本地化后台表单的text spinbutton：区分编辑草稿与数值状态，支持精度、步进、越界策略、可逆格式化与完整Field/FormValueBridge合同。',
		status: 'stable',
		keywords: [
			'number field',
			'spinbutton',
			'intl',
			'locale',
			'precision',
			'parser',
			'formatter',
			'form'
		],
		profiles: ['form-control', 'animated'],
		capabilities: [
			'controlled',
			'invalid',
			'form-data',
			'form-reset',
			'composition',
			'variants-and-states',
			'accessible-name',
			'basic-render',
			'focus',
			'keyboard',
			'locale',
			'uncontrolled',
			'disabled',
			'readonly',
			'external-clear',
			'density',
			'native-props'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'pin-input',
		name: 'ZPinInput',
		category: 'input',
		summary:
			'单一nullable字符串、Field owner和FormValueBridge驱动的OTP/PIN输入，覆盖grapheme/IME、整段粘贴/autofill、动态length、受控清空与外部form。',
		status: 'stable',
		keywords: [
			'pin input',
			'otp',
			'one-time-code',
			'paste',
			'autofill',
			'IME',
			'Unicode grapheme',
			'form reset',
			'rtl'
		],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'accessible-name',
			'form-data',
			'form-reset',
			'keyboard',
			'disabled',
			'native-props',
			'controlled',
			'external-clear',
			'readonly',
			'rtl'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'field',
		name: 'ZField',
		category: 'input',
		summary: '统一关联label、description、错误、表单状态与唯一焦点owner的无侵入字段容器。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'basic-render',
			'controlled',
			'invalid',
			'disabled',
			'readonly',
			'accessible-name',
			'focus',
			'keyboard'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'fieldset',
		name: 'ZFieldset',
		category: 'input',
		summary: '真实fieldset与第一legend组织多个独立字段，并保留浏览器整组禁用语义。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'native-props',
			'controlled',
			'disabled',
			'form-data',
			'density',
			'variants-and-states'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'file-upload',
		name: 'ZFileUpload',
		category: 'input',
		summary:
			'生产FilePicker/queue边界：原生选择与拖放只创建typed队列，组件管理可控状态、进度、AbortSignal、重试和FormData；transport由调用方注入，默认手动且不拥有URL、fetch、凭据、响应、缓存或分片策略。',
		status: 'stable',
		keywords: [
			'file picker',
			'file upload',
			'drop zone',
			'typed queue',
			'transport adapter',
			'abort signal',
			'retry',
			'progress',
			'formdata',
			'readonly'
		],
		profiles: ['form-control', 'animated'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'invalid',
			'keyboard',
			'uncontrolled',
			'loading',
			'resource-cleanup',
			'controlled',
			'external-clear',
			'disabled',
			'focus',
			'readonly',
			'locale'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'form',
		name: 'ZForm',
		category: 'input',
		summary:
			'ZForm可注入唯一FormModel，由ZFormField把字段路径提供给适配控件自动读写；Standard Schema消费模型输入并产生typed output，原生FormData仍独立遵守successful controls规则。FieldPath图统一拥有依赖验证、错误分层、竞态和首错导航。',
		status: 'stable',
		keywords: [
			'form',
			'standard schema',
			'async validation',
			'aria-busy',
			'first error',
			'field path',
			'dependency graph',
			'controller',
			'server errors',
			'dirty',
			'touched',
			'field array',
			'form list'
		],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'invalid',
			'loading',
			'resource-cleanup',
			'native-props',
			'disabled',
			'form-reset'
		],
		demoCount: 13,
		publicComponentCount: 3
	},
	{
		id: 'radio-group',
		name: 'ZRadioGroup',
		category: 'input',
		summary:
			'真实radio承担FormData/required，LogicalCollection、SelectionModel与MountedElements分别承担typed选项、选择和roving焦点。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'native-props',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'external-clear',
			'focus',
			'disabled',
			'invalid',
			'rtl',
			'readonly'
		],
		demoCount: 6,
		publicComponentCount: 2
	},
	{
		id: 'range-slider',
		name: 'ZRangeSlider',
		category: 'input',
		summary: '两个真实range共享domain与表单字段，并以明确碰撞策略维护已排序二元范围。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'controlled',
			'focus',
			'keyboard',
			'uncontrolled',
			'variants-and-states',
			'form-data',
			'form-reset',
			'native-props',
			'composition',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'rating',
		name: 'ZRating',
		category: 'input',
		summary: '真实radio保留评分键盘、FormData与reset，视觉层负责fraction预览和可替换符号。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'controlled',
			'focus',
			'native-props',
			'variants-and-states',
			'disabled',
			'form-data',
			'form-reset',
			'readonly',
			'composition',
			'density',
			'keyboard',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'select',
		name: 'ZSelect',
		category: 'input',
		summary:
			'生产单选集合：options模式在未挂载时仍拥有完整typed-key顺序，compound模式保持兼容；SelectionModel、ActiveDescendant、Popover与FormValueBridge分别拥有选择、焦点、浮层和提交。',
		status: 'stable',
		keywords: [
			'select',
			'listbox',
			'logical collection',
			'active descendant',
			'typed key',
			'async',
			'group',
			'virtual list',
			'form reset'
		],
		profiles: ['form-control', 'collection', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'controlled',
			'focus',
			'resource-cleanup',
			'loading',
			'locale',
			'portal',
			'external-clear',
			'readonly',
			'accessible-name',
			'rtl'
		],
		demoCount: 8,
		publicComponentCount: 4
	},
	{
		id: 'segmented',
		name: 'ZSegmented',
		category: 'input',
		summary:
			'LogicalCollection、SelectionModel、MountedElements和FormValueBridge分别拥有typed options、选择、roving焦点与表单值的Segmented。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'native-props',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'external-clear',
			'focus',
			'disabled',
			'rtl',
			'readonly'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'toggle-group',
		name: 'ZToggleGroup',
		category: 'input',
		summary:
			'用真实button与aria-pressed表达单/多选切换，不使用radiogroup语义；焦点导航与选择状态保持正交。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'controlled',
			'focus',
			'keyboard',
			'variants-and-states',
			'form-data',
			'form-reset',
			'native-props',
			'basic-render',
			'composition',
			'disabled',
			'readonly',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'toolbar',
		name: 'ZToolbar',
		category: 'navigation',
		summary:
			'以一个Toolbar焦点集合组合异构原生控件；ZToolbarItem不产生DOM，只为真实控件提供焦点和禁用属性。',
		status: 'experimental',
		keywords: [],
		profiles: ['collection', 'primitive'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'focus',
			'keyboard',
			'native-props',
			'readonly',
			'variants-and-states'
		],
		demoCount: 4,
		publicComponentCount: 2
	},
	{
		id: 'nav-link',
		name: 'ZNavLink',
		category: 'navigation',
		summary:
			'以真实anchor、button或被动内容呈现导航行；当前页、子级展开、disabled和视觉tone保持独立。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive', 'collection'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'native-props',
			'variants-and-states',
			'composition',
			'focus',
			'keyboard',
			'rtl',
			'reduced-motion'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'splitter',
		name: 'ZSplitter',
		category: 'layout',
		summary:
			'以真实panel snippet、ARIA separator和pointer/keyboard生命周期调整可约束的多面板布局。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'composition',
			'focus',
			'keyboard',
			'native-props',
			'variants-and-states',
			'controlled',
			'rtl'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'sortable',
		name: 'ZSortable',
		category: 'layout',
		summary:
			'受控顺序的可排序集合：手柄拖动、键盘与可见前后移动操作共用一个接受和取消流程。FormList组合继续使用现有FormArray.move，拖动预览不会改写表单。',
		status: 'experimental',
		keywords: ['sortable', 'reorder', 'drag', 'keyboard', 'form list', 'async'],
		profiles: ['collection'],
		capabilities: [
			'controlled',
			'keyboard',
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'invalid'
		],
		demoCount: 2,
		publicComponentCount: 1
	},
	{
		id: 'navigation-menu',
		name: 'ZNavigationMenu',
		category: 'navigation',
		summary:
			'以真实nav列表、链接和disclosure构建站点导航；current、focus、open和SPA路由请求由独立owner管理。',
		status: 'experimental',
		keywords: [],
		profiles: ['collection', 'layer'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'keyboard',
			'focus',
			'native-props',
			'variants-and-states',
			'rtl',
			'controlled'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'anchor',
		name: 'ZAnchor',
		category: 'navigation',
		summary:
			'以真实anchor追踪和定位页面section，active观察、路由current、滚动容器和hash历史由各自owner管理。',
		status: 'experimental',
		keywords: [],
		profiles: ['collection', 'primitive'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'native-props',
			'controlled',
			'focus',
			'variants-and-states',
			'keyboard',
			'rtl',
			'reduced-motion',
			'ssr'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'menubar',
		name: 'ZMenubar',
		category: 'navigation',
		summary: '协调多个既有DropdownMenu的单开状态和根级menuitem焦点，菜单命令仍由ZMenu拥有。',
		status: 'experimental',
		keywords: [],
		profiles: ['collection', 'layer'],
		capabilities: [
			'accessible-name',
			'basic-render',
			'composition',
			'keyboard',
			'controlled',
			'rtl',
			'variants-and-states',
			'focus'
		],
		demoCount: 3,
		publicComponentCount: 4
	},
	{
		id: 'resizable',
		name: 'ZResizable',
		category: 'layout',
		summary:
			'以逻辑边/角handle调整单一真实元素的inline/block尺寸，保留单位、约束和完整pointer/keyboard生命周期。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'focus',
			'keyboard',
			'native-props',
			'composition',
			'variants-and-states',
			'rtl'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'copy-button',
		name: 'ZCopyButton',
		category: 'gene',
		summary:
			'复用Button和owner Window ClipboardController提供真实用户手势复制、成功/失败反馈与可清理异步生命周期。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive', 'form-control'],
		capabilities: [
			'basic-render',
			'focus',
			'native-props',
			'variants-and-states',
			'composition',
			'controlled',
			'resource-cleanup'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'affix',
		name: 'ZAffix',
		category: 'layout',
		summary: '使用真实sticky或明确的滚动owner投影，不隐藏占位与边界。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive'],
		capabilities: [
			'basic-render',
			'native-props',
			'composition',
			'resource-cleanup',
			'variants-and-states'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'back-top',
		name: 'ZBackTop',
		category: 'navigation',
		summary: '真实button调用原生scrollTo；局部容器示例不会改变Docs整页位置。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive', 'animated'],
		capabilities: [
			'basic-render',
			'focus',
			'native-props',
			'composition',
			'resource-cleanup',
			'full-motion',
			'reduced-motion',
			'variants-and-states'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'password-input',
		name: 'ZPasswordInput',
		category: 'input',
		summary: '一个持久的ZInput拥有值、表单和焦点；独立真实button只切换password/text。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive', 'form-control'],
		capabilities: [
			'basic-render',
			'controlled',
			'focus',
			'native-props',
			'form-data',
			'form-reset',
			'composition',
			'variants-and-states'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'native-select',
		name: 'ZNativeSelect',
		category: 'input',
		summary: '保留浏览器原生select、有效性、FormData与reset语义。',
		status: 'experimental',
		keywords: [],
		profiles: ['primitive', 'form-control'],
		capabilities: [
			'basic-render',
			'controlled',
			'native-props',
			'variants-and-states',
			'focus',
			'form-data',
			'form-reset',
			'resource-cleanup'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'switch',
		name: 'ZSwitch',
		category: 'input',
		summary:
			'真实checkbox驱动的双态设置开关，覆盖受控与非受控状态、Field、原生表单、异步busy和方向/动画偏好。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control', 'animated'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'uncontrolled',
			'form-data',
			'form-reset',
			'native-props',
			'density',
			'disabled',
			'invalid',
			'loading',
			'readonly',
			'accessible-name',
			'focus',
			'full-motion',
			'keyboard',
			'reduced-motion',
			'rtl'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'tags-input',
		name: 'ZTagsInput',
		category: 'input',
		summary:
			'生产级string-only TagsInput：独立values/draft owner、ZTag复用、方向键标签焦点、批量粘贴、可选编辑、视觉overflow与多值FormValueBridge保持正交。',
		status: 'stable',
		keywords: [
			'tags input',
			'tag group',
			'draft ownership',
			'paste',
			'IME',
			'editable tag',
			'overflow',
			'form values'
		],
		profiles: ['collection', 'data-view', 'form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'invalid',
			'readonly',
			'controlled',
			'external-clear',
			'focus',
			'resource-cleanup',
			'ssr',
			'native-props'
		],
		demoCount: 7,
		publicComponentCount: 1
	},
	{
		id: 'textarea',
		name: 'ZTextarea',
		category: 'input',
		summary: '原生textarea、Field/Form合同与跨document共享测量器组成的有界多行文本控件。',
		status: 'stable',
		keywords: ['textarea', 'autosize', 'minRows', 'maxRows', 'form', 'field', 'IME', 'resize'],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'external-clear',
			'keyboard',
			'native-props',
			'resource-cleanup',
			'disabled',
			'focus',
			'invalid',
			'readonly',
			'form-data',
			'form-reset',
			'uncontrolled'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'time-field',
		name: 'ZTimeField',
		category: 'input',
		summary:
			'本地化Time分段字段：Intl顺序、12/24小时、hour/minute/second granularity与step、nullable owner、不可用值、Field/FormValueBridge/reset和复合bare外观；编辑保留已有值的隐藏精度。',
		status: 'stable',
		keywords: ['time field', 'segments', 'hour cycle', 'granularity', 'step', 'nullable'],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'basic-render',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'readonly',
			'accessible-name',
			'locale',
			'rtl',
			'controlled',
			'external-clear',
			'focus',
			'invalid',
			'native-props'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'time-picker',
		name: 'ZTimePicker',
		category: 'input',
		summary:
			'实验性 Time Picker：以唯一 Time/null owner 组合可编辑 TimeField、有限时间列、复用 ZPopover 和真实表单语义；面板选择先进入草稿，确认后提交。',
		status: 'experimental',
		keywords: ['time picker', 'time field', 'popover', 'draft', 'controlled', 'form', 'nullable'],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'controlled',
			'portal',
			'basic-render',
			'external-clear',
			'focus',
			'keyboard',
			'invalid',
			'variants-and-states',
			'disabled',
			'readonly',
			'density',
			'form-data',
			'form-reset',
			'uncontrolled'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'time-range-picker',
		name: 'ZTimeRangePicker',
		category: 'input',
		summary:
			'实验性时间范围选择器，复用两个 TimeField 和共享 TimePickerPanel。根组件独占范围模型、打开状态及两个 FormData 端点；明确区分同日有序与跨午夜范围。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'basic-render',
			'controlled',
			'keyboard',
			'portal',
			'disabled',
			'readonly',
			'form-data',
			'form-reset'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'date-time-field',
		name: 'ZDateTimeField',
		category: 'input',
		summary:
			'组合日期与时间分段的实验性字段。local 值为 CalendarDateTime，zoned 值为 ZonedDateTime；根节点独占模型和一个 FormData 条目。当前仅支持 Gregorian 日历编辑。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'basic-render',
			'controlled',
			'external-clear',
			'keyboard',
			'form-data',
			'form-reset'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'date-time-picker',
		name: 'ZDateTimePicker',
		category: 'input',
		summary:
			'由 DateTimeField、Calendar 和共享时间面板组合的实验性选择器。根组件唯一持有值、打开状态与表单条目，local/zoned 类型明确，面板支持确认或即时提交。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'composition',
			'form-data',
			'form-reset',
			'controlled',
			'basic-render',
			'external-clear',
			'keyboard',
			'portal',
			'invalid',
			'locale',
			'density',
			'disabled',
			'readonly'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'date-time-range-picker',
		name: 'ZDateTimeRangePicker',
		category: 'input',
		summary:
			'实验性日期时间范围选择器。两个 DateTimeField 与一个共享 DateTimePickerPanel 组合，根组件唯一管理范围值、表单端点和提交策略，支持 local/zoned、部分范围与显式排序。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'layer'],
		capabilities: [
			'composition',
			'controlled',
			'basic-render',
			'portal',
			'keyboard',
			'locale',
			'invalid',
			'density',
			'disabled',
			'readonly',
			'form-data',
			'form-reset'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'period-calendar',
		name: 'ZPeriodCalendar',
		category: 'input',
		summary:
			'同一个周期日历覆盖月份、年份、季度和周，并支持单选、多选与范围。周期是带种类和规则的冻结记录，日期边界由共享算法计算，不使用某一天冒充整个月或季度。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'accessible-name',
			'composition',
			'keyboard',
			'basic-render',
			'locale',
			'controlled',
			'form-data',
			'form-reset',
			'invalid'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'period-picker',
		name: 'ZPeriodPicker',
		category: 'input',
		summary:
			'以PeriodCalendar、Popover和InputGroup组合的周期选择器。四种granularity、三种selectionMode共用唯一模型、序列化、焦点与主题，不维护平行的月份/年份/周/季度状态机。',
		status: 'experimental',
		keywords: [],
		profiles: ['form-control', 'layer', 'collection'],
		capabilities: [
			'basic-render',
			'keyboard',
			'portal',
			'controlled',
			'density',
			'readonly',
			'disabled',
			'form-data',
			'form-reset'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'time-grid',
		name: 'ZTimeGrid',
		category: 'input',
		summary:
			'TimeGrid接收显式、唯一且有序的Time时隙，不解析字符串或自行生成日期状态。slot标签可由业务命名，也可按Provider locale和hourCycle格式化。',
		status: 'experimental',
		keywords: ['time grid', 'time slots', 'radio group', 'nullable', 'form', 'rtl'],
		profiles: ['form-control', 'collection'],
		capabilities: [
			'basic-render',
			'controlled',
			'keyboard',
			'locale',
			'form-data',
			'invalid',
			'disabled',
			'readonly',
			'rtl'
		],
		demoCount: 3,
		publicComponentCount: 1
	},
	{
		id: 'time-value',
		name: 'ZTimeValue',
		category: 'data-display',
		summary:
			'TimeValue只把Time格式化为本地化文本，并复用ZText的字号、行高、字重、tone和溢出能力；它没有编辑、时区或表单owner。',
		status: 'experimental',
		keywords: ['time value', 'intl', 'locale', 'hour cycle', 'semantic time', 'typography'],
		profiles: ['data-view'],
		capabilities: [
			'basic-render',
			'locale',
			'native-props',
			'variants-and-states',
			'accessible-name',
			'composition'
		],
		demoCount: 2,
		publicComponentCount: 1
	},
	{
		id: 'tree-select',
		name: 'ZTreeSelect',
		category: 'input',
		summary:
			'TreeSelect只拥有value/open/Field/FormValue与Popover组合；层级、expanded、active、selection、lazy和virtual全部委托同一个ZTree。',
		status: 'stable',
		keywords: [
			'tree select',
			'logical tree',
			'popover',
			'clear',
			'lazy children',
			'virtual tree',
			'form value'
		],
		profiles: ['collection', 'form-control', 'layer', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'uncontrolled',
			'controlled',
			'external-clear',
			'keyboard',
			'disabled',
			'readonly',
			'loading',
			'portal',
			'resource-cleanup',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'transfer',
		name: 'ZTransfer',
		category: 'input',
		summary:
			'生产双栏Transfer：完整LogicalCollection是唯一数据顺序，来源/目标view和两套SelectionModel分别拥有过滤与临时勾选，最终value、FormData和异步孤儿由Root独立拥有；两栏可共享固定行VirtualList而不复制状态。',
		status: 'stable',
		keywords: [
			'transfer',
			'dual list',
			'logical collection',
			'multiple selection',
			'filter',
			'virtual list',
			'async orphan',
			'form reset',
			'readonly'
		],
		profiles: ['form-control', 'collection', 'data-view', 'virtualized'],
		capabilities: [
			'composition',
			'variants-and-states',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'disabled',
			'readonly',
			'accessible-name',
			'locale',
			'rtl',
			'controlled',
			'external-clear',
			'loading',
			'focus',
			'resource-cleanup'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'slider',
		name: 'ZSlider',
		category: 'input',
		summary: '真实range驱动、支持Field/RTL/readonly、受控状态和原生表单的单值Slider。',
		status: 'stable',
		keywords: [],
		profiles: ['form-control'],
		capabilities: [
			'composition',
			'variants-and-states',
			'controlled',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'density',
			'disabled',
			'invalid',
			'native-props',
			'focus',
			'readonly'
		],
		demoCount: 5,
		publicComponentCount: 1
	},
	{
		id: 'accordion',
		name: 'ZAccordion',
		category: 'navigation',
		summary:
			'生产Accordion compound collection：组件props保持扁平以服务Svelte绑定和ComponentProps，严格single/multiple helper服务静态配置，运行时仍校验值shape并保留LogicalCollection、active焦点、nested与Presence。',
		status: 'stable',
		keywords: [
			'accordion',
			'logical collection',
			'typed key',
			'roving focus',
			'presence',
			'nested',
			'flat props',
			'single helper',
			'multiple helper'
		],
		profiles: ['collection', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'controlled',
			'focus',
			'keyboard',
			'uncontrolled',
			'external-clear',
			'resource-cleanup',
			'accessible-name',
			'native-props',
			'rtl',
			'full-motion',
			'reduced-motion'
		],
		demoCount: 8,
		publicComponentCount: 4
	},
	{
		id: 'command',
		name: 'ZCommand',
		category: 'navigation',
		summary:
			'生产Command collection：输入保持唯一DOM焦点，LogicalCollection与ActiveDescendant拥有typed结果导航，相关性排序或外部结果owner保持正交，并用本地化live status公告结果数量。',
		status: 'stable',
		keywords: ['command', 'ranked filter', 'active descendant', 'keyboard', 'action'],
		profiles: ['collection'],
		capabilities: [
			'variants-and-states',
			'composition',
			'controlled',
			'focus',
			'keyboard',
			'locale',
			'uncontrolled',
			'loading',
			'resource-cleanup'
		],
		demoCount: 4,
		publicComponentCount: 1
	},
	{
		id: 'command-palette',
		name: 'ZCommandPalette',
		category: 'navigation',
		summary:
			'CommandPalette只组合ZCommand的筛选/active-descendant与ZDialog的模态焦点/Portal，并以显式DOM作用域快捷键协调打开；路由、异步请求和业务确认由调用方拥有。',
		status: 'stable',
		keywords: ['command palette', 'dialog', 'shortcut', 'focus trap', 'modal'],
		profiles: ['collection', 'layer'],
		capabilities: [
			'variants-and-states',
			'composition',
			'accessible-name',
			'focus',
			'keyboard',
			'portal',
			'controlled',
			'external-clear',
			'resource-cleanup'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'context-menu',
		name: 'ZContextMenu',
		category: 'navigation',
		summary:
			'真实pointer client坐标与键盘目标logical start只负责更新零尺寸锚点，Popup生命周期继续由Popover唯一拥有，内容完整复用ZMenu。',
		status: 'stable',
		keywords: ['context menu', 'right click', 'Shift F10', 'pointer coordinates', 'submenu', 'RTL'],
		profiles: ['collection', 'layer', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'accessible-name',
			'focus',
			'full-motion',
			'keyboard',
			'portal',
			'disabled',
			'controlled',
			'uncontrolled',
			'resource-cleanup',
			'reduced-motion',
			'rtl'
		],
		demoCount: 6,
		publicComponentCount: 3
	},
	{
		id: 'dropdown-menu',
		name: 'ZDropdownMenu',
		category: 'navigation',
		summary:
			'Popover唯一拥有controlled open、Portal、Floating、dismiss、Presence与焦点恢复；Content只接入共享ZMenu及未取消action后的关闭策略。',
		status: 'stable',
		keywords: [
			'dropdown menu',
			'menu button',
			'submenu',
			'controlled open',
			'focus restore',
			'floating'
		],
		profiles: ['collection', 'layer', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'focus',
			'full-motion',
			'keyboard',
			'portal',
			'disabled',
			'controlled',
			'uncontrolled',
			'resource-cleanup',
			'rtl',
			'native-props',
			'reduced-motion'
		],
		demoCount: 6,
		publicComponentCount: 3
	},
	{
		id: 'menu',
		name: 'ZMenu',
		category: 'navigation',
		summary:
			'LogicalCollection拥有typed顺序、禁用与typeahead文本，MountedElements仅把当前挂载节点接到roving focus；action、selection与nested submenu共用同一事件链。',
		status: 'stable',
		keywords: [
			'menu',
			'submenu',
			'checkbox item',
			'radio item',
			'link item',
			'roving focus',
			'typeahead'
		],
		profiles: ['collection'],
		capabilities: [
			'variants-and-states',
			'composition',
			'accessible-name',
			'basic-render',
			'disabled',
			'keyboard',
			'controlled',
			'uncontrolled',
			'focus',
			'portal',
			'resource-cleanup',
			'rtl',
			'native-props'
		],
		demoCount: 6,
		publicComponentCount: 11
	},
	{
		id: 'pagination',
		name: 'ZPagination',
		category: 'navigation',
		summary:
			'生产分页导航：用互斥totalPages/totalItems合同避免双重总量事实，提供受控页尺寸、三种呈现、RTL和动态焦点恢复，但把请求、URL、筛选与DataTable状态留给调用方owner。',
		status: 'stable',
		keywords: [
			'pagination',
			'page size',
			'total items',
			'simple',
			'compact',
			'rtl',
			'keyboard',
			'data table',
			'server controlled'
		],
		profiles: ['data-view'],
		capabilities: [
			'variants-and-states',
			'composition',
			'controlled',
			'focus',
			'keyboard',
			'locale',
			'native-props',
			'accessible-name',
			'rtl',
			'disabled',
			'uncontrolled'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'tabs',
		name: 'ZTabs',
		category: 'navigation',
		summary:
			'生产Tabs compound collection：LogicalCollection/MountedElements/CollectionNavigation分离逻辑顺序、DOM和active焦点；nullable typed selection支持automatic/manual、动态nearest恢复、RTL/IME和明确Panel挂载策略。',
		status: 'stable',
		keywords: [
			'tabs',
			'logical collection',
			'typed key',
			'manual activation',
			'panel lifecycle',
			'rtl'
		],
		profiles: ['collection'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'controlled',
			'focus',
			'keyboard',
			'uncontrolled',
			'external-clear',
			'native-props',
			'resource-cleanup',
			'ssr',
			'accessible-name',
			'locale',
			'rtl'
		],
		demoCount: 7,
		publicComponentCount: 4
	},
	{
		id: 'tree',
		name: 'ZTree',
		category: 'navigation',
		summary:
			'LogicalTree只规范完整typed层级；SelectionModel、CollectionNavigation、ActiveDescendant、lazy coordinator和ZVirtualList分别拥有选择、active、DOM、请求与窗口。',
		status: 'stable',
		keywords: [
			'tree',
			'logical tree',
			'active descendant',
			'lazy children',
			'virtual tree',
			'large data',
			'selection',
			'typeahead'
		],
		profiles: ['collection', 'form-control', 'virtualized'],
		capabilities: [
			'variants-and-states',
			'composition',
			'controlled',
			'form-data',
			'form-reset',
			'keyboard',
			'uncontrolled',
			'focus',
			'rtl',
			'loading',
			'locale',
			'resource-cleanup',
			'ssr'
		],
		demoCount: 6,
		publicComponentCount: 1
	},
	{
		id: 'alert-dialog',
		name: 'ZAlertDialog',
		category: 'overlay',
		summary:
			'强制显式决策的modal alertdialog：默认Cancel焦点，pending统一锁定Action/Cancel/dismiss，caller拥有Promise与错误展示。',
		status: 'stable',
		keywords: [],
		profiles: ['layer', 'animated'],
		capabilities: [
			'accessible-name',
			'focus',
			'keyboard',
			'portal',
			'controlled',
			'variants-and-states',
			'loading',
			'resource-cleanup',
			'invalid',
			'ssr'
		],
		demoCount: 5,
		publicComponentCount: 8
	},
	{
		id: 'dialog',
		name: 'ZDialog',
		category: 'overlay',
		summary:
			'modal-only Dialog根，统一Portal/Layer/Presence；Content拥有真实ARIA引用、typed outside事件与initial/restore焦点策略。',
		status: 'stable',
		keywords: [],
		profiles: ['layer', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'focus',
			'keyboard',
			'portal',
			'resource-cleanup',
			'controlled',
			'native-props',
			'accessible-name',
			'ssr'
		],
		demoCount: 6,
		publicComponentCount: 7
	},
	{
		id: 'drawer',
		name: 'ZDrawer',
		category: 'overlay',
		summary:
			'复用Dialog的modal生命周期，提供四个逻辑方向、主题预设与CSS尺寸、窄屏边界和完整进出场动画。',
		status: 'stable',
		keywords: [],
		profiles: ['layer', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'controlled',
			'focus',
			'keyboard',
			'portal',
			'ssr',
			'uncontrolled',
			'resource-cleanup',
			'full-motion',
			'reduced-motion',
			'rtl'
		],
		demoCount: 6,
		publicComponentCount: 7
	},
	{
		id: 'popconfirm',
		name: 'ZPopconfirm',
		category: 'overlay',
		summary:
			'Popover继续唯一拥有定位、dismiss与焦点恢复；Popconfirm只增加最小Promise generation、pending防重复和安全可访问错误，不接管transport或业务重试。',
		status: 'stable',
		keywords: [
			'popconfirm',
			'confirmation',
			'async confirm',
			'pending',
			'generation',
			'focus restore'
		],
		profiles: ['layer', 'animated'],
		capabilities: [
			'basic-render',
			'focus',
			'full-motion',
			'keyboard',
			'portal',
			'controlled',
			'variants-and-states',
			'reduced-motion',
			'resource-cleanup',
			'accessible-name'
		],
		demoCount: 5,
		publicComponentCount: 7
	},
	{
		id: 'popover',
		name: 'ZPopover',
		category: 'overlay',
		summary:
			'元素Trigger上的modal/nonmodal浮层：Floating、nested branch、typed dismiss、显式ARIA和owner-realm Presence共享一个open owner。',
		status: 'stable',
		keywords: [],
		profiles: ['layer', 'animated'],
		capabilities: [
			'basic-render',
			'focus',
			'keyboard',
			'portal',
			'native-props',
			'variants-and-states',
			'composition',
			'controlled',
			'external-clear',
			'accessible-name'
		],
		demoCount: 5,
		publicComponentCount: 3
	},
	{
		id: 'tooltip',
		name: 'ZTooltip',
		category: 'overlay',
		summary:
			'focus即时打开；pointer hover通过作用域Group共享warmup/cooldown并保持唯一active；Content可停留但持续拒绝任何可聚焦或交互后代。',
		status: 'stable',
		keywords: [
			'tooltip',
			'tooltip group',
			'hysteresis',
			'disabled trigger',
			'hoverable content',
			'focus'
		],
		profiles: ['layer', 'animated', 'service'],
		capabilities: [
			'variants-and-states',
			'composition',
			'basic-render',
			'controlled',
			'focus',
			'keyboard',
			'portal',
			'full-motion',
			'resource-cleanup',
			'accessible-name',
			'disabled',
			'native-props',
			'reduced-motion',
			'rtl'
		],
		demoCount: 6,
		publicComponentCount: 4
	},
	{
		id: 'tour',
		name: 'ZTour',
		category: 'overlay',
		summary:
			'生产导览层：受控open/step、作用域安全target、缺失目标close/skip/wait策略、显式居中步骤、typed locale、RTL、Portal/Floating、联合焦点branch和reduced-motion Presence；不复制页面路由、异步请求或业务完成状态。',
		status: 'stable',
		keywords: [
			'tour',
			'spotlight',
			'floating',
			'focus scope',
			'portal',
			'missing target',
			'root scope',
			'rtl',
			'locale',
			'reduced motion'
		],
		profiles: ['layer', 'animated'],
		capabilities: [
			'variants-and-states',
			'composition',
			'controlled',
			'focus',
			'keyboard',
			'portal',
			'resource-cleanup',
			'locale',
			'rtl',
			'reduced-motion'
		],
		demoCount: 5,
		publicComponentCount: 1
	}
] as readonly ComponentCatalogManifestEntry[]);
export const componentCatalogManifestById = new Map(
	componentCatalogManifest.map((entry) => [entry.id, entry])
);
