// Generated by scripts/generate-catalog-manifest.mjs. Do not edit.
import type { ComponentDoc } from './component-doc.js';
export const componentDocLoaders = {
	provider: () =>
		import('../content/components/gene/provider/doc.js').then((module) => module.providerDoc),
	box: () => import('../content/components/gene/box/doc.js').then((module) => module.boxDoc),
	stack: () =>
		import('../content/components/layout/stack/doc.js').then((module) => module.stackDoc),
	text: () => import('../content/components/gene/text/doc.js').then((module) => module.textDoc),
	heading: () =>
		import('../content/components/gene/heading/doc.js').then((module) => module.headingDoc),
	icon: () => import('../content/components/gene/icon/doc.js').then((module) => module.iconDoc),
	code: () => import('../content/components/gene/code/doc.js').then((module) => module.codeDoc),
	button: () =>
		import('../content/components/gene/button/doc.js').then((module) => module.buttonDoc),
	'toggle-button': () =>
		import('../content/components/gene/toggle-button/doc.js').then(
			(module) => module.toggleButtonDoc
		),
	link: () => import('../content/components/gene/link/doc.js').then((module) => module.linkDoc),
	separator: () =>
		import('../content/components/gene/separator/doc.js').then((module) => module.separatorDoc),
	'visually-hidden': () =>
		import('../content/components/gene/visually-hidden/doc.js').then(
			(module) => module.visuallyHiddenDoc
		),
	kbd: () => import('../content/components/gene/kbd/doc.js').then((module) => module.kbdDoc),
	'aspect-ratio': () =>
		import('../content/components/layout/aspect-ratio/doc.js').then(
			(module) => module.aspectRatioDoc
		),
	container: () =>
		import('../content/components/layout/container/doc.js').then((module) => module.containerDoc),
	avatar: () =>
		import('../content/components/data-display/avatar/doc.js').then((module) => module.avatarDoc),
	badge: () =>
		import('../content/components/data-display/badge/doc.js').then((module) => module.badgeDoc),
	card: () =>
		import('../content/components/data-display/card/doc.js').then((module) => module.cardDoc),
	'description-list': () =>
		import('../content/components/data-display/description-list/doc.js').then(
			(module) => module.descriptionListDoc
		),
	list: () =>
		import('../content/components/data-display/list/doc.js').then((module) => module.listDoc),
	tag: () =>
		import('../content/components/data-display/tag/doc.js').then((module) => module.tagDoc),
	progress: () =>
		import('../content/components/data-display/progress/doc.js').then(
			(module) => module.progressDoc
		),
	meter: () =>
		import('../content/components/data-display/meter/doc.js').then((module) => module.meterDoc),
	skeleton: () =>
		import('../content/components/data-display/skeleton/doc.js').then(
			(module) => module.skeletonDoc
		),
	empty: () =>
		import('../content/components/data-display/empty/doc.js').then((module) => module.emptyDoc),
	timeline: () =>
		import('../content/components/data-display/timeline/doc.js').then(
			(module) => module.timelineDoc
		),
	statistic: () =>
		import('../content/components/data-display/statistic/doc.js').then(
			(module) => module.statisticDoc
		),
	table: () =>
		import('../content/components/data-display/table/doc.js').then((module) => module.tableDoc),
	'virtual-list': () =>
		import('../content/components/data-display/virtual-list/doc.js').then(
			(module) => module.virtualListDoc
		),
	'data-table': () =>
		import('../content/components/data-display/data-table/doc.js').then(
			(module) => module.dataTableDoc
		),
	carousel: () =>
		import('../content/components/data-display/carousel/doc.js').then(
			(module) => module.carouselDoc
		),
	alert: () =>
		import('../content/components/feedback/alert/doc.js').then((module) => module.alertDoc),
	'loading-bar': () =>
		import('../content/components/feedback/loading-bar/doc.js').then(
			(module) => module.loadingBarDoc
		),
	result: () =>
		import('../content/components/feedback/result/doc.js').then((module) => module.resultDoc),
	spinner: () =>
		import('../content/components/feedback/spinner/doc.js').then((module) => module.spinnerDoc),
	toast: () =>
		import('../content/components/feedback/toast/doc.js').then((module) => module.toastDoc),
	checkbox: () =>
		import('../content/components/input/checkbox/doc.js').then((module) => module.checkboxDoc),
	calendar: () =>
		import('../content/components/input/calendar/doc.js').then((module) => module.calendarDoc),
	cascader: () =>
		import('../content/components/input/cascader/doc.js').then((module) => module.cascaderDoc),
	'color-picker': () =>
		import('../content/components/input/color-picker/doc.js').then(
			(module) => module.colorPickerDoc
		),
	combobox: () =>
		import('../content/components/input/combobox/doc.js').then((module) => module.comboboxDoc),
	'date-field': () =>
		import('../content/components/input/date-field/doc.js').then((module) => module.dateFieldDoc),
	'date-picker': () =>
		import('../content/components/input/date-picker/doc.js').then((module) => module.datePickerDoc),
	'date-range-picker': () =>
		import('../content/components/input/date-range-picker/doc.js').then(
			(module) => module.dateRangePickerDoc
		),
	input: () => import('../content/components/input/input/doc.js').then((module) => module.inputDoc),
	'input-group': () =>
		import('../content/components/input/input-group/doc.js').then((module) => module.inputGroupDoc),
	mention: () =>
		import('../content/components/input/mention/doc.js').then((module) => module.mentionDoc),
	'multi-select': () =>
		import('../content/components/input/multi-select/doc.js').then(
			(module) => module.multiSelectDoc
		),
	'number-field': () =>
		import('../content/components/input/number-field/doc.js').then(
			(module) => module.numberFieldDoc
		),
	'pin-input': () =>
		import('../content/components/input/pin-input/doc.js').then((module) => module.pinInputDoc),
	field: () => import('../content/components/input/field/doc.js').then((module) => module.fieldDoc),
	'file-upload': () =>
		import('../content/components/input/file-upload/doc.js').then((module) => module.fileUploadDoc),
	form: () => import('../content/components/input/form/doc.js').then((module) => module.formDoc),
	'radio-group': () =>
		import('../content/components/input/radio-group/doc.js').then((module) => module.radioGroupDoc),
	select: () =>
		import('../content/components/input/select/doc.js').then((module) => module.selectDoc),
	segmented: () =>
		import('../content/components/input/segmented/doc.js').then((module) => module.segmentedDoc),
	switch: () =>
		import('../content/components/input/switch/doc.js').then((module) => module.switchDoc),
	'tags-input': () =>
		import('../content/components/input/tags-input/doc.js').then((module) => module.tagsInputDoc),
	textarea: () =>
		import('../content/components/input/textarea/doc.js').then((module) => module.textareaDoc),
	'time-field': () =>
		import('../content/components/input/time-field/doc.js').then((module) => module.timeFieldDoc),
	'tree-select': () =>
		import('../content/components/input/tree-select/doc.js').then((module) => module.treeSelectDoc),
	transfer: () =>
		import('../content/components/input/transfer/doc.js').then((module) => module.transferDoc),
	slider: () =>
		import('../content/components/input/slider/doc.js').then((module) => module.sliderDoc),
	accordion: () =>
		import('../content/components/navigation/accordion/doc.js').then(
			(module) => module.accordionDoc
		),
	command: () =>
		import('../content/components/navigation/command/doc.js').then((module) => module.commandDoc),
	'command-palette': () =>
		import('../content/components/navigation/command-palette/doc.js').then(
			(module) => module.commandPaletteDoc
		),
	'context-menu': () =>
		import('../content/components/navigation/context-menu/doc.js').then(
			(module) => module.contextMenuDoc
		),
	'dropdown-menu': () =>
		import('../content/components/navigation/dropdown-menu/doc.js').then(
			(module) => module.dropdownMenuDoc
		),
	menu: () =>
		import('../content/components/navigation/menu/doc.js').then((module) => module.menuDoc),
	pagination: () =>
		import('../content/components/navigation/pagination/doc.js').then(
			(module) => module.paginationDoc
		),
	tabs: () =>
		import('../content/components/navigation/tabs/doc.js').then((module) => module.tabsDoc),
	tree: () =>
		import('../content/components/navigation/tree/doc.js').then((module) => module.treeDoc),
	'alert-dialog': () =>
		import('../content/components/overlay/alert-dialog/doc.js').then(
			(module) => module.alertDialogDoc
		),
	dialog: () =>
		import('../content/components/overlay/dialog/doc.js').then((module) => module.dialogDoc),
	drawer: () =>
		import('../content/components/overlay/drawer/doc.js').then((module) => module.drawerDoc),
	popconfirm: () =>
		import('../content/components/overlay/popconfirm/doc.js').then(
			(module) => module.popconfirmDoc
		),
	popover: () =>
		import('../content/components/overlay/popover/doc.js').then((module) => module.popoverDoc),
	tooltip: () =>
		import('../content/components/overlay/tooltip/doc.js').then((module) => module.tooltipDoc),
	tour: () => import('../content/components/overlay/tour/doc.js').then((module) => module.tourDoc)
} satisfies Record<string, () => Promise<ComponentDoc>>;
