// Generated by scripts/check-progress-summary.mjs. Do not edit by hand.
export const zuiProgress = {
	schemaVersion: 1,
	package: {
		name: '@zadmin/zui',
		version: '0.1.0'
	},
	api: {
		components: 169,
		declaredProps: 2141,
		metadataGapProps: 0,
		fallbackProps: 0
	},
	maturity: {
		Declared: 169,
		Authorable: 169,
		ContractVerified: 169,
		RuntimeImplemented: 169,
		BrowserBehaviorVerified: 160,
		VisuallyVerified: 157,
		DesktopVerified: 0,
		ProductionVerified: 164,
		statuses: {
			experimental: 28,
			stable: 141
		}
	},
	stability: {
		stableCompliant: 141,
		stableViolations: 0,
		promotionEligibleExperimental: 17
	},
	docs: {
		routes: {
			componentCount: 102,
			guideCount: 9,
			totalCount: 112
		},
		deployed: false
	},
	support: {
		node: '24',
		pnpm: '11.22.0',
		browsers: ['chromium', 'firefox', 'webkit'],
		ssrCsp: true,
		webview: true,
		miniapp: true
	},
	release: {
		status: 'blocked',
		passedChecks: 26,
		totalChecks: 31,
		blocked: [
			'releasePublishTarballReuse',
			'npmOidcProvenance',
			'automatedTagAndGithubRelease',
			'registrySmoke',
			'versionedDocs'
		]
	},
	nextPriorities: [
		{
			id: 'production-evidence',
			remaining: 5,
			description: '为尚未ProductionVerified的组件补真实production browser/SSR合同。'
		},
		{
			id: 'visual-evidence',
			remaining: 12,
			description: '补齐组件级几何、computed style或截图证据；普通浏览器交互断言不再冒充视觉验证。'
		},
		{
			id: 'stable-promotion',
			remaining: 17,
			description: '逐项审查已满足门禁的experimental组件；禁止自动批量晋级。'
		},
		{
			id: 'desktop-evidence',
			remaining: 169,
			description: '建立组件级WebView2/Desktop证据后再提升DesktopVerified。'
		},
		{
			id: 'release-boundary',
			remaining: 5,
			description: '完成真实publish/OIDC/tag/registry smoke与版本化Docs部署边界。'
		}
	]
} as const;
