// Generated by scripts/check-progress-summary.mjs. Do not edit by hand.
export const zuiProgress = {
	schemaVersion: 2,
	package: {
		name: '@zadmin/zui',
		version: '0.1.0'
	},
	api: {
		components: 187,
		declaredProps: 2679,
		metadataGapProps: 0,
		fallbackProps: 0
	},
	maturity: {
		MetadataDeclared: 187,
		PublicExportPresent: 187,
		ApiContractDeclared: 187,
		RuntimeImplemented: 187,
		BrowserBehaviorContractsDeclared: 175,
		VisualContractsDeclared: 161,
		ProductionContractsDeclared: 179,
		SsrContractsDeclared: 184,
		execution: {
			BrowserBehaviorVerified: 0,
			VisuallyVerified: 0,
			ProductionVerified: 0,
			DesktopVerified: 0
		},
		executionStatus: {
			status: 'pending',
			revision: null,
			source: null,
			detail:
				'No repository manifest binds per-component browser, production, or visual results to the current commit.'
		},
		currentRevisionVerified: 0,
		statuses: {
			experimental: 46,
			stable: 141
		}
	},
	stability: {
		stableCompliant: 0,
		stablePendingExecution: 141,
		stableViolations: 0,
		promotionEligibleExperimental: 0
	},
	docs: {
		routes: {
			componentCount: 117,
			guideCount: 9,
			totalCount: 127
		},
		deployed: false
	},
	support: {
		node: '24',
		pnpm: '11.22.0',
		browsers: ['chromium', 'firefox', 'webkit'],
		ssrCsp: true,
		webview: true,
		miniapp: true
	},
	release: {
		status: 'blocked',
		passedChecks: 26,
		totalChecks: 31,
		blocked: [
			'releasePublishTarballReuse',
			'npmOidcProvenance',
			'automatedTagAndGithubRelease',
			'registrySmoke',
			'versionedDocs'
		]
	},
	nextPriorities: [
		{
			id: 'production-contract-assets',
			remaining: 8,
			description: '为缺少production browser/SSR合同资产的组件补明确测试。'
		},
		{
			id: 'current-revision-execution',
			remaining: 187,
			description:
				'用现有revision-bound执行制品证明当前commit的browser与production合同真实通过；无制品保持pending。'
		},
		{
			id: 'visual-contract-assets',
			remaining: 26,
			description: '补齐组件级几何、computed style或截图合同资产；资产存在不等于视觉执行通过。'
		},
		{
			id: 'stable-promotion',
			remaining: 0,
			description: '逐项审查已满足门禁的experimental组件；禁止自动批量晋级。'
		},
		{
			id: 'desktop-evidence',
			remaining: 187,
			description: '建立组件级WebView2/Desktop证据后再提升DesktopVerified。'
		},
		{
			id: 'release-boundary',
			remaining: 5,
			description: '完成真实publish/OIDC/tag/registry smoke与版本化Docs部署边界。'
		}
	]
} as const;
