import { readFileSync, readdirSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { ZUI_PACKAGE_NAME } from '../src/entrypoints/index.js';
import {
	accordionContentMetadata,
	accordionItemMetadata,
	accordionMetadata,
	accordionTriggerMetadata,
	alertDialogActionMetadata,
	alertDialogCancelMetadata,
	alertDialogContentMetadata,
	alertDialogDescriptionMetadata,
	alertDialogMetadata,
	alertDialogOverlayMetadata,
	alertDialogTitleMetadata,
	alertDialogTriggerMetadata,
	aspectRatioMetadata,
	boxMetadata,
	buttonMetadata,
	cascaderMetadata,
	checkboxMetadata,
	comboboxContentMetadata,
	comboboxInputMetadata,
	comboboxItemMetadata,
	comboboxMetadata,
	commandMetadata,
	commandPaletteMetadata,
	codeMetadata,
	containerMetadata,
	contextMenuContentMetadata,
	contextMenuMetadata,
	contextMenuTriggerMetadata,
	dialogCloseMetadata,
	dialogContentMetadata,
	dialogDescriptionMetadata,
	dialogMetadata,
	dialogOverlayMetadata,
	dialogTitleMetadata,
	dialogTriggerMetadata,
	dropdownMenuContentMetadata,
	dropdownMenuMetadata,
	dropdownMenuTriggerMetadata,
	drawerCloseMetadata,
	drawerContentMetadata,
	drawerDescriptionMetadata,
	drawerMetadata,
	drawerOverlayMetadata,
	drawerTitleMetadata,
	drawerTriggerMetadata,
	fieldMetadata,
	iconMetadata,
	inputMetadata,
	inputGroupMetadata,
	kbdMetadata,
	linkMetadata,
	menuGroupMetadata,
	menuItemMetadata,
	menuLabelMetadata,
	menuMetadata,
	menuSeparatorMetadata,
	mentionMetadata,
	multiSelectContentMetadata,
	multiSelectItemMetadata,
	multiSelectMetadata,
	multiSelectTriggerMetadata,
	numberFieldMetadata,
	pinInputMetadata,
	paginationMetadata,
	popconfirmActionMetadata,
	popconfirmCancelMetadata,
	popconfirmContentMetadata,
	popconfirmDescriptionMetadata,
	popconfirmMetadata,
	popconfirmTitleMetadata,
	popconfirmTriggerMetadata,
	popoverContentMetadata,
	popoverMetadata,
	popoverTriggerMetadata,
	providerMetadata,
	radioGroupItemMetadata,
	radioGroupMetadata,
	separatorMetadata,
	selectContentMetadata,
	selectItemMetadata,
	selectMetadata,
	selectTriggerMetadata,
	segmentedMetadata,
	sliderMetadata,
	stackMetadata,
	switchMetadata,
	tabsListMetadata,
	tabsMetadata,
	tabsPanelMetadata,
	tabsTriggerMetadata,
	tagsInputMetadata,
	textareaMetadata,
	textMetadata,
	tooltipContentMetadata,
	tooltipMetadata,
	tooltipTriggerMetadata,
	treeMetadata,
	treeSelectMetadata,
	transferMetadata,
	toggleButtonMetadata,
	visuallyHiddenMetadata
} from '../src/entrypoints/metadata.js';

interface PackageManifest {
	readonly exports: Readonly<Record<string, unknown>>;
	readonly publishConfig: { readonly exports: Readonly<Record<string, unknown>> };
	readonly scripts: { readonly build: string };
}

const manifest = JSON.parse(
	readFileSync(new URL('../package.json', import.meta.url), 'utf8')
) as PackageManifest;

describe('@zadmin/zui package', () => {
	it('keeps a stable public package name', () => {
		expect(ZUI_PACKAGE_NAME).toBe('@zadmin/zui');
	});

	it('keeps source and publish exports aligned with the entrypoint directory', () => {
		expect(readdirSync(new URL('../src/entrypoints/', import.meta.url)).sort()).toEqual([
			'code.ts',
			'compiler.ts',
			'index.ts',
			'internal.ts',
			'layer.ts',
			'metadata.ts',
			'runtime.ts',
			'testing.ts',
			'theme.ts',
			'themes.ts'
		]);
		expect(Object.keys(manifest.exports)).toEqual(['.', './*']);
		expect(Object.keys(manifest.publishConfig.exports)).toEqual(['.', './*']);
		expect(manifest.exports).not.toHaveProperty('./core');
		expect(manifest.scripts.build).toContain('--input src');
		expect(JSON.stringify(manifest)).not.toContain('src/lib');
	});

	it('keeps component metadata unique and colocated with public source files', () => {
		const metadata = [
			accordionMetadata,
			accordionItemMetadata,
			accordionTriggerMetadata,
			accordionContentMetadata,
			alertDialogMetadata,
			alertDialogTriggerMetadata,
			alertDialogOverlayMetadata,
			alertDialogContentMetadata,
			alertDialogTitleMetadata,
			alertDialogDescriptionMetadata,
			alertDialogCancelMetadata,
			alertDialogActionMetadata,
			dialogMetadata,
			dialogTriggerMetadata,
			dialogOverlayMetadata,
			dialogContentMetadata,
			dialogTitleMetadata,
			dialogDescriptionMetadata,
			dialogCloseMetadata,
			dropdownMenuMetadata,
			dropdownMenuTriggerMetadata,
			dropdownMenuContentMetadata,
			drawerMetadata,
			drawerTriggerMetadata,
			drawerOverlayMetadata,
			drawerContentMetadata,
			drawerTitleMetadata,
			drawerDescriptionMetadata,
			drawerCloseMetadata,
			providerMetadata,
			boxMetadata,
			stackMetadata,
			textMetadata,
			iconMetadata,
			codeMetadata,
			buttonMetadata,
			cascaderMetadata,
			radioGroupMetadata,
			radioGroupItemMetadata,
			checkboxMetadata,
			comboboxMetadata,
			commandMetadata,
			commandPaletteMetadata,
			comboboxInputMetadata,
			comboboxContentMetadata,
			comboboxItemMetadata,
			toggleButtonMetadata,
			linkMetadata,
			menuMetadata,
			menuGroupMetadata,
			menuLabelMetadata,
			menuItemMetadata,
			menuSeparatorMetadata,
			mentionMetadata,
			multiSelectMetadata,
			multiSelectTriggerMetadata,
			numberFieldMetadata,
			pinInputMetadata,
			multiSelectContentMetadata,
			multiSelectItemMetadata,
			paginationMetadata,
			popconfirmMetadata,
			popconfirmTriggerMetadata,
			popconfirmContentMetadata,
			popconfirmTitleMetadata,
			popconfirmDescriptionMetadata,
			popconfirmCancelMetadata,
			popconfirmActionMetadata,
			popoverMetadata,
			popoverTriggerMetadata,
			popoverContentMetadata,
			separatorMetadata,
			selectMetadata,
			selectTriggerMetadata,
			selectContentMetadata,
			selectItemMetadata,
			segmentedMetadata,
			sliderMetadata,
			visuallyHiddenMetadata,
			kbdMetadata,
			aspectRatioMetadata,
			containerMetadata,
			contextMenuMetadata,
			contextMenuTriggerMetadata,
			contextMenuContentMetadata,
			inputMetadata,
			inputGroupMetadata,
			fieldMetadata,
			switchMetadata,
			tabsMetadata,
			tabsListMetadata,
			tabsTriggerMetadata,
			tabsPanelMetadata,
			tagsInputMetadata,
			textareaMetadata,
			tooltipMetadata,
			tooltipTriggerMetadata,
			tooltipContentMetadata,
			treeMetadata,
			treeSelectMetadata,
			transferMetadata
		];
		expect(new Set(metadata.map(({ id }) => id)).size).toBe(metadata.length);
		expect(metadata.every(({ name }) => name.startsWith('Z'))).toBe(true);
		expect(metadata.every(({ name, source }) => source.endsWith(`/${name}.svelte`))).toBe(true);
	});
});
